# Upstream changes from _extends are only recognized when modifications are made to this file in the default branch.
_extends: .github
repository:
  name: terraform-aws-refarch-utils
  description: An opinionated module for working with shared data in the Cloud Posse reference architecture
  homepage: https://cloudposse.com/accelerate
  topics: ""

